### ISSUE TITLE
Sinatra RuntimeError

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/what-is-sinatra#17]
The lesson says after you do `gem install sinatra` and set up your  `app.rb` to be (if you're on the IDE):

```
require 'sinatra'

# Add these two lines below if you're on the Learn IDE!
set :bind, ENV["HOST_IP"]
set :port, ENV["HTTP_PORT"]

get '/' do
  "Hello, World!"
end
```

Then when you run `ruby app.rb` you should have a running Sinatra server on `SOME_IP:SOME_PORT`, but instead, this is coming up:

```
// ♥ ruby app.rb
== Sinatra (v2.0.0) has taken the stage on  for development with backup from Thin
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 67.205.130.239:8080, CTRL+C to stop
Stopping ...
== Sinatra has ended his set (crowd applauds)
/usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.2/lib/thin/backends/tcp_server.rb:16:in `connect'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.2/lib/thin/backends/base.rb:63:in `block in start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/handler/thin.rb:22:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1522:in `start_server'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1456:in `run!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/sinatra-2.0.0/lib/sinatra/main.rb:26:in `block in <module:Sinatra>'
```

If I ran: `echo $HTTP_PORT` it showed up blank, so I tried substituting `RACK_PORT` and hard-coding a port# instead of `HTTP_PORT`, but just got the same message but for a different port.

**Comment by bhollan** [comment]
I also tried re-installing `sinatra` at a different level, but it didn't change anything.  I don't think this is a version conflict anywhere because it's talking about privileges and "port in use" and stuff.

**Comment by bhollan** [comment]
Was able to launch locally.  Output:

```
== Sinatra (v2.0.0) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
Use Ctrl-C to stop
127.0.0.1 - - [30/Oct/2017:15:18:10 -0600] "GET / HTTP/1.1" 200 13 0.1249
127.0.0.1 - - [30/Oct/2017:15:18:11 -0600] "GET / HTTP/1.1" 200 13 0.0007
127.0.0.1 - - [30/Oct/2017:15:18:11 -0600] "GET /favicon.ico HTTP/1.1" 404 469 0.0017


^C== Sinatra has ended his set (crowd applauds)
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2017-10-30 15:18:15 -0600 ===
- Goodbye!
```
